export const API_REVIEW = 'http://eva-komi.ru/api/review'
export const API_COUNTRY = 'http://eva-komi.ru/api/country'
export const API_BRAND = 'http://eva-komi.ru/api/brand'
export const API_USER = 'http://eva-komi.ru/api/user'
export const API_IMAGES = 'http://eva-komi.ru/api/image'
