export const API_REVIEW = 'http://cosmeticreviews.ru/api/review'
export const API_COUNTRY = 'http://cosmeticreviews.ru/api/country'
export const API_BRAND = 'http://cosmeticreviews.ru/api/brand'
export const API_USER = 'http://cosmeticreviews.ru/api/user'
export const API_IMAGES = 'http://cosmeticreviews.ru/api/image'
export const IMAGES_SERVER = 'http://cosmeticreviews.ru/images/'
export const API_COMMENT = 'http://cosmeticreviews.ru/api/comment'
