export const API_REVIEW = 'https://cosmeticreviews.ru/api/review'
export const API_COUNTRY = 'https://cosmeticreviews.ru/api/country'
export const API_BRAND = 'https://cosmeticreviews.ru/api/brand'
export const API_USER = 'https://cosmeticreviews.ru/api/user'
export const API_IMAGES = 'https://cosmeticreviews.ru/api/image'
export const IMAGES_SERVER = 'https://cosmeticreviews.ru/images/'
export const API_COMMENT = 'https://cosmeticreviews.ru/api/comment'
export const LOG = 'https://cosmeticreviews.ru/api/log'
